version: "2.1"

volumes:
  pika-conf:
    driver_opts:
      type: none
      device: ${PK_BASE}/conf
      o: bind
  pika-logs:
    driver_opts:
      type: none
      device: ${PK_BASE}/logs
      o: bind
  pika-data:
    driver_opts:
      type: none
      device: ${PK_BASE}/data
      o: bind

networks:
  pika-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PK_DOCKER_SUBNET}
